[package]
name = "rethink-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core types, HA MQTT, ThinQ device acceptors, config for rethink"

[dependencies]
rethink-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
